### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by allanlaal** [oxodao/YoutubeClock#3]
please add a LICENSE file to make this legit opensource :)

**Comment by allanlaal** [comment]
needed by https://github.com/code-for-charity/Wish-Factory/issues/5

**Comment by oxodao** [comment]
Updated. Releasing as MIT

https://github.com/oxodao/YoutubeClock/blob/master/LICENSE.MD

**Comment by ImprovedTube** [comment]
Awesome!
